FROM node:22-alpine

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN apk add --no-cache openssl libc6-compat

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend
COPY package.json ./package.json
COPY turbo.json ./turbo.json
COPY pnpm-lock.yaml ./pnpm-lock.yaml
COPY pnpm-workspace.yaml ./pnpm-workspace.yaml   

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm run db:generate

# Build all packages first (including workspace packages)
RUN pnpm --filter '@repo/*' build

# Build the http-backend app
RUN pnpm --filter http-backend build

EXPOSE 8080

CMD ["pnpm", "run", "start:backend"]
